# This is a config for E2B sandbox template.
# You can use template ID (8zg1ozluww6svu2vt43j) or template name (webgenie-devlo-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("webgenie-devlo-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("webgenie-devlo-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('webgenie-devlo-2')

team_id = "a29339f6-68e5-4921-9d37-77b9f36ee961"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "webgenie-devlo-2"
template_id = "8zg1ozluww6svu2vt43j"
